seed: 42
symbols:
- EURUSD
- GBPUSD
- USDJPY
- USDCHF
- AUDUSD
- USDCAD
- NZDUSD
timeframes:
  D1:
    years: 20
    seq_len: 128
    horizon: 2
    atr_mult: 1.3
    sl_mult: 1.2
    tp1_mult: 1.8
    tp2_mult: 3.0
  H4:
    years: 20
    seq_len: 96
    horizon: 4
    atr_mult: 1.2
    sl_mult: 1.1
    tp1_mult: 1.6
    tp2_mult: 2.5
  H2:
    years: 10
    seq_len: 96
    horizon: 5
    atr_mult: 1.1
    sl_mult: 1.0
    tp1_mult: 1.5
    tp2_mult: 2.2
  H1:
    years: 10
    seq_len: 96
    horizon: 6
    atr_mult: 1.0
    sl_mult: 1.0
    tp1_mult: 1.4
    tp2_mult: 2.0
  M30:
    years: 5
    seq_len: 64
    horizon: 8
    atr_mult: 0.9
    sl_mult: 0.9
    tp1_mult: 1.2
    tp2_mult: 1.8
  M15:
    years: 5              # 5 років історії для M15
    seq_len: 96           # Більше свічок = 24 години (1 день контексту)
    horizon: 12           # 12 свічок = 3 години (реалістичніший таргет)
    atr_mult: 0.9         # Трохи більше для фільтрації шуму
    sl_mult: 0.9          # Трохи більше простору
    tp1_mult: 1.2         # Реалістичні цілі
    tp2_mult: 1.8
thresholds:
  prob: 0.5
